In [1]:
import syft
import syft.nn as nn
from syft.controller import tensors
import imp
imp.reload(syft.controller)
imp.reload(syft.nn)
imp.reload(syft)

import numpy as np
from syft import FloatTensor, IntTensor

/Users/gavin/anaconda2/envs/openmined/lib/python3.6/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated since IPython 4.0. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
Import warning: PyTorch capabilities not available due to torch module not found on your system
How to install PyTorch: http://pytorch.org/

In [2]:
# FloatTensor Init
a = FloatTensor(np.array([-1,-2,3,4,5,-6]).astype('float'))
b = FloatTensor(np.array([-30,-32,33,34,35,-36]).astype('float'))

In [3]:
# FloatTensor Add Elem
a + 5

[  4.   3.   8.   9.  10.  -1.]
[syft.FloatTensor:3 grad:None size:6 c:[] p:[1, 4] init:add_scalar]

	-----------creators-----------
	[syft.FloatTensor:1 grad:None size:6 c:[3] p:[] init:]
	[syft.FloatTensor:4 grad:None size:1 c:[] p:[] init:add_scalar]
	------------------------------



In [4]:
# FloatTensor Add Scalar
a + b

[-31. -34.  36.  38.  40. -42.]
[syft.FloatTensor:5 grad:None size:6 c:[] p:[1, 2] init:add_elem]

	-----------creators-----------
	[syft.FloatTensor:1 grad:None size:6 c:[3, 5] p:[] init:]
	[syft.FloatTensor:2 grad:None size:6 c:[5] p:[] init:]
	------------------------------



In [5]:
# FloatTensor GPU
a = FloatTensor(np.array([-1,-2,3,4,5,-6]).astype('float'))
b = FloatTensor(np.array([-30,-32,33,34,35,-36]).astype('float'))
a.gpu()
b.gpu()

[-30. -32.  33.  34.  35. -36.]
[syft.FloatTensor:7 grad:None size:6 c:[] p:[] init:]

In [6]:
# FloatTensor Add Elem GPU
a + 5

[  4.   3.   8.   9.  10.  -1.]
[syft.FloatTensor:8 grad:None size:6 c:[] p:[6, 9] init:add_scalar]

	-----------creators-----------
	[syft.FloatTensor:6 grad:None size:6 c:[8] p:[] init:]
	[syft.FloatTensor:9 grad:None size:1 c:[] p:[] init:add_scalar]
	------------------------------



In [7]:
# FloatTensor Add Scalar GPU
a + b

[-31. -34.  36.  38.  40. -42.]
[syft.FloatTensor:10 grad:None size:6 c:[] p:[6, 7] init:add_elem]

	-----------creators-----------
	[syft.FloatTensor:6 grad:None size:6 c:[8, 10] p:[] init:]
	[syft.FloatTensor:7 grad:None size:6 c:[10] p:[] init:]
	------------------------------



In [8]:
# IntTensor Init
a = IntTensor(np.array([-1,-2,3,4,5,-6]))
b = IntTensor(np.array([-30,-32,33,34,35,-36]))

In [9]:
# IntTensor Add Elem
a + 5

[ 4  3  8  9 10 -1]
[syft.IntTensor:3 size:6]

In [10]:
# IntTensor Add Scalar
a + b

[-31 -34  36  38  40 -42]
[syft.IntTensor:4 size:6]

In [11]:
# IntTensor GPU
a = IntTensor(np.array([-1,-2,3,4,5,-6]))
b = IntTensor(np.array([-30,-32,33,34,35,-36]))
a.gpu()
b.gpu()

[-30 -32  33  34  35 -36]
[syft.IntTensor:6 size:6]

In [12]:
# IntTensor Add Elem GPU
a + 5

[ 4  3  8  9 10 -1]
[syft.IntTensor:7 size:6]

In [13]:
# IntTensor Add Elem CPU
a + b

[-31 -34  36  38  40 -42]
[syft.IntTensor:8 size:6]