In [1]:
import syft
import syft.nn as nn
from syft.controller import tensors
import imp
imp.reload(syft.controller)
imp.reload(syft.nn)
imp.reload(syft)

import numpy as np
from syft import FloatTensor, IntTensor

/Users/gavin/anaconda2/envs/openmined/lib/python3.6/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated since IPython 4.0. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
Import warning: PyTorch capabilities not available due to torch module not found on your system
How to install PyTorch: http://pytorch.org/

In [2]:
# FloatTensor Init
a = FloatTensor(np.array([-1,-2,3,4,5,-6]).astype('float'))
b = FloatTensor(np.array([-30,-32,33,34,35,-36]).astype('float'))

In [3]:
# FloatTensor Add Elem
a + 5

[  4.   3.   8.   9.  10.  -1.]
[syft.FloatTensor:56 grad:None size:6 c:[] p:[54, 57] init:add_scalar]

	-----------creators-----------
	[syft.FloatTensor:54 grad:None size:6 c:[56] p:[] init:]
	[syft.FloatTensor:57 grad:None size:1 c:[] p:[] init:add_scalar]
	------------------------------



In [4]:
# FloatTensor Add Scalar
a + b

[-31. -34.  36.  38.  40. -42.]
[syft.FloatTensor:58 grad:None size:6 c:[] p:[54, 55] init:add_elem]

	-----------creators-----------
	[syft.FloatTensor:54 grad:None size:6 c:[56, 58] p:[] init:]
	[syft.FloatTensor:55 grad:None size:6 c:[58] p:[] init:]
	------------------------------



In [5]:
# FloatTensor GPU
a = FloatTensor(np.array([-1,-2,3,4,5,-6]).astype('float'))
b = FloatTensor(np.array([-30,-32,33,34,35,-36]).astype('float'))
a.gpu()
b.gpu()

[-30. -32.  33.  34.  35. -36.]
[syft.FloatTensor:60 grad:None size:6 c:[] p:[] init:]

In [6]:
# FloatTensor Add Elem GPU
a + 5

[  4.   3.   8.   9.  10.  -1.]
[syft.FloatTensor:61 grad:None size:6 c:[] p:[59, 62] init:add_scalar]

	-----------creators-----------
	[syft.FloatTensor:59 grad:None size:6 c:[61] p:[] init:]
	[syft.FloatTensor:62 grad:None size:1 c:[] p:[] init:add_scalar]
	------------------------------



In [7]:
# FloatTensor Add Scalar GPU
a + b

[-31. -34.  36.  38.  40. -42.]
[syft.FloatTensor:63 grad:None size:6 c:[] p:[59, 60] init:add_elem]

	-----------creators-----------
	[syft.FloatTensor:59 grad:None size:6 c:[61, 63] p:[] init:]
	[syft.FloatTensor:60 grad:None size:6 c:[63] p:[] init:]
	------------------------------



In [8]:
# IntTensor Init
a = IntTensor(np.array([-1,-2,3,4,5,-6]))
b = IntTensor(np.array([-30,-32,33,34,35,-36]))

In [9]:
# IntTensor Add Elem
a + 5

[ 4  3  8  9 10 -1]
[syft.IntTensor:31 size:6]

In [10]:
# IntTensor Add Scalar
a + b

[-31 -34  36  38  40 -42]
[syft.IntTensor:32 size:6]

In [11]:
# IntTensor GPU
a = IntTensor(np.array([-1,-2,3,4,5,-6]))
b = IntTensor(np.array([-30,-32,33,34,35,-36]))
a.gpu()
b.gpu()

AttributeError: 'IntTensor' object has no attribute 'gpu'

In [12]:
# IntTensor Add Elem GPU
c + 5

NameError: name 'c' is not defined

In [13]:
# IntTensor Add Elem CPU
c + d

NameError: name 'c' is not defined